USE QueryRepetitionEntity
GO


/*
-- SELECT TANKS THAT HAVE GERMAN GUNS
SELECT * 
FROM Tanks AS TNK
WHERE TNK.GunId IN

(SELECT GNS.Id
FROM Guns AS GNS
WHERE GNS.ManufacturerId IN 

(SELECT MFC.Id
FROM Manufacturers AS MFC
WHERE MFC.CountryName = 'Germany'))
*/


/*
-- SELECT ALL TANKS WITH ENGINE HP LT 1500
SELECT *
FROM Tanks AS TNK
WHERE TNK.EngineId IN

(SELECT ENG.Id
FROM Engines AS ENG
WHERE ENG.HorsePowers < 1500)
*/


/*
-- SELECT SOME TANK(S) WITH THE MOST WEALTHY MANUFACTURER
SELECT *
FROM Tanks AS TNK
WHERE TNK.ManufacturerId IN 

(SELECT MFC.Id
FROM Manufacturers AS MFC
WHERE MFC.BudgetId IN

(SELECT BDG.Id
FROM Budgets AS BDG
WHERE BDG.Value IN

(SELECT MAX(BGD.Value)
FROM Budgets AS BGD)))
*/



/*
-- TODO:

-- 1. MAKE A GREAT TABLE VIEW OF ALL MACHINES AND THEIR DEVICES
-- 2. MAKE A GREAT TABLE VIEW OF ALL MANUFACTURERS COMPARED

*/